"use client";

import PostSearch from '@/components/PostSearch';
import Posts from '@/components/Posts';
import { getAllPosts } from "@/services/getPosts";
import { Metadata } from "next";
import { useEffect, useState } from "react";

// При экспорте метаданных выдает ошибку.
/* export const metadata: Metadata = {
  title: "Blog | Next App",
  description: "Generated by create next app",
}; */

// Клиентские компоненты не могут быть асинхронными.
export default function Blog() {
  const [posts, setPosts] = useState<any[]>([]);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    getAllPosts()
      .then((res) => {
        setPosts(res);
      })
      .finally(() => {
        setLoading(false);
      });
  }, []);

  return (
    <>
      <h1>Blog</h1>
      <PostSearch onSearch={setPosts}/>
      {loading ? (
        <h3>Loading posts</h3>
      ) : (
        <Posts posts={posts}/>
      )}
    </>
  );
}
