import type { Metadata } from "next";
import { Inter } from "next/font/google";

import ReduxProvider from "@/store/ReduxProvider";

// Components.
import TheHeader from "@/components/TheHeader";
import TheFooter from "@/components/TheFooter";

import "./globals.css";
import ProviderForSession from '@/components/Providers';

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        {/* Хук useSession из контекста достаёт сессию */}
        <ProviderForSession>
        <ReduxProvider>
          <TheHeader />
          <main className="container">{children}</main>
          <TheFooter />
        </ReduxProvider>
        </ProviderForSession>
      </body>
    </html>
  );
}
