import "./globals.css"; // Здесь подключаются глобальные стити. Css-переменные, шрифты, нормалайзы.

import type { Metadata } from "next"; //
import { Inter } from "next/font/google"; // Здесь подключаются гугл шрифты предосавленные из коробки. Прикольно.

// Components.
import TheHeader from "@/components/TheHeader";
import TheFooter from "@/components/TheFooter";

const inter = Inter({ subsets: ["latin"] }); // Шрифты импортируются ввиде функции. Параметром передается объект с характеристиками шрифтов.

// Объект отвечающий за метаданные корневого layout. Типизируется сигнарутой из Metadata из библиотеки Next.
// Этот объект должен экспортироваться отсюда. Это настройка SEO.
export const metadata: Metadata = {
  title: "Next App",
  description: "Generated by create next app",
};

/*
  Сюда попадают открытыие page. Например мы открываем /about. Компонент соответствующий app/about/page.tsx -> About(), будет попадать в этот компонент как children.

  То есть page будет зарендерина в <body></body>
*/

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      {/* В className мы передаем строку className которую получаем из объекта возвращенного функцией Inter. Можем этого не делать*/}
      <body className={inter.className}>
      <TheHeader />
        <main className='container'>{children}</main>
      <TheFooter />
      </body>
    </html>
  );
}
